scriptencoding utf-8
lang C
if &compatible
	set nocompatible
endif

colorscheme atom-dark-256

" Fixups for colorscheme
function! FixColorscheme()
       highlight! IncSearch ctermfg=172 ctermbg=16
       highlight! Error term=reverse ctermfg=white ctermbg=red guifg=white guibg=red
endfun

augroup fix_color_scheme
       autocmd!
       autocmd ColorScheme * call FixColorscheme()
augroup end

source ~/.vim/mod/set.vim
source ~/.vim/mod/bindings.vim
source ~/.vim/mod/filetypes.vim

" Start a local ~/.vimrc_local, if it exists
let s:vimrc_local_name='~/.vimrc_local'
if !empty(glob(s:vimrc_local_name))
	execute 'source' s:vimrc_local_name
endif

set printoptions=paper:a4
set printexpr=system('/usr/local/bin/lpr'\ .\ (&printdevice\ ==\ ''\ ?\ ''\ :\ '\ -P'\ .\ &printdevice)\ .\ '\ '\ .\ v:fname_in)\ .\ delete(v:fname_in)\ +\ v:shell_error

source ~/.vim/mod/project.vim
source ~/.vim/mod/plugins.vim
