#!/bin/sh

for wrapper in /usr/local/lib*/neomutt/pgpewrap; do
	if test -e "$wrapper"; then
		echo $wrapper
		PATH=$PATH:$(dirname $wrapper)
		export PATH
	fi
done

if which neomutt; then
	CMD=neomutt
else
	CMD=mutt
fi

exec $CMD $@
