#!/bin/sh

# This script should be run from cron.
# Here is an example entry, consisting of two lines:
#
# @reboot /bin/rm -f ~/.mbsync-lock
# * * * * * /usr/bin/lockf -s -t 0 ~/.mutt/sync-maildir

/usr/local/bin/mbsync -a 2> /dev/null
if [ $? -ne 0 ]; then
	echo "mbsync failed.\n"
fi

/usr/local/bin/notmuch new --quiet 2> /dev/null
if [ $? -ne 0 ]; then
	echo "notmuch update failed.\n"
fi

exit 0
